In [67]:
import pandas as pd
import numpy as np

In [68]:

shots = pd.read_csv("../data/shots_hometeam_2024season.csv")

shots.head()

   id              name  goalie_id  period  x_location  y_location  is_home
0   2  Kristen Campbell         64       1         448          63        1
1   2  Kristen Campbell         64       1         549         182        1
2   2  Kristen Campbell         64       1         387         225        1
3   2  Kristen Campbell         64       1         541         134        1
4   2  Kristen Campbell         64       1         474         105        1

In [ ]:

# sql:
# SELECT games.id, goalie.name, shots.goalie_id, shots.period, shots.x_location, shots.y_location, IF(player_teams.team_id = games.home_team_id, 1, 0) AS is_home 
# FROM shots 
# JOIN players n
# AS goalie 
# ON shots.goalie_id = goalie.id 
# JOIN games ON shots.game_id = games.id 
# JOIN player_teams 
# ON goalie.id = player_teams.player_id 
# AND player_teams.start_date != "0000-00-00"
# WHERE games.season = 1;


def do_math(x, home):
    if home == 1:
        return (600 - x)
    else:
        return x



shots["x_location"] = shots.apply(lambda x: do_math(x["x_location"], x["is_home"]), axis=1)

In [60]:
shots.head()

   id              name  goalie_id  period  x_location  y_location  is_home
0   2  Kristen Campbell         64       1         152          63        1
1   2  Kristen Campbell         64       1          51         182        1
2   2  Kristen Campbell         64       1         213         225        1
3   2  Kristen Campbell         64       1          59         134        1
4   2  Kristen Campbell         64       1         126         105        1

In [61]:
shots.describe()

,id,goalie_id,period,x_location,y_location,is_home
count,4106.000000,4106.000000,4106.000000,4106.000000,4106.000000,4106.000000
mean,39.046517,61.768875,2.056016,115.336094,150.649537,0.481734
std,21.339173,46.412296,0.854182,55.748557,62.774310,0.499727
min,2.000000,6.000000,1.000000,16.000000,6.000000,0.000000
25%,20.000000,22.000000,1.000000,68.000000,106.000000,0.000000
50%,39.000000,59.000000,2.000000,105.000000,152.000000,0.000000
75%,57.000000,85.000000,3.000000,152.000000,195.000000,1.000000
max,83.000000,155.000000,4.000000,298.000000,294.000000,1.000000

In [62]:

# distance from net:
# let's say the net is at (585, 150)
# max x = 588, max y = 298

# a rink is 200 ft long = 2400 inches long
# therefore each unit of x is 4 inches
# a rink is 85 ft wide = 1020 inches
# therefore each unit of x is about 3.4

# distance between two points is sqrt((x1 - x2)^2 + (y1 - y2)^2)

In [63]:
shots["x_ft"] = shots["x_location"] * 4 / 12
shots["y_ft"] = shots["y_location"] * 3.4 / 12
shots["distance_ft"] = round(np.sqrt((shots["x_ft"] - 11)**2 + (shots["y_ft"] - (42.5))**2), 2)

In [64]:
shots.head()

,id,name,goalie_id,period,x_location,y_location,is_home,x_ft,y_ft,distance_ft
0,2,Kristen Campbell,64,1,152,63,1,50.666667,17.850000,46.70
1,2,Kristen Campbell,64,1,51,182,1,17.000000,51.566667,10.87
2,2,Kristen Campbell,64,1,213,225,1,71.000000,63.750000,63.65
3,2,Kristen Campbell,64,1,59,134,1,19.666667,37.966667,9.78
4,2,Kristen Campbell,64,1,126,105,1,42.000000,29.750000,33.52

In [65]:
shots.describe()

,id,goalie_id,period,x_location,y_location,is_home,x_ft,y_ft,distance_ft
count,4106.000000,4106.000000,4106.000000,4106.000000,4106.000000,4106.000000,4106.000000,4106.000000,4106.000000
mean,39.046517,61.768875,2.056016,115.336094,150.649537,0.481734,38.445365,42.684036,32.611266
std,21.339173,46.412296,0.854182,55.748557,62.774310,0.499727,18.582852,17.786055,18.745029
min,2.000000,6.000000,1.000000,16.000000,6.000000,0.000000,5.333333,1.700000,1.870000
25%,20.000000,22.000000,1.000000,68.000000,106.000000,0.000000,22.666667,30.033333,16.865000
50%,39.000000,59.000000,2.000000,105.000000,152.000000,0.000000,35.000000,43.066667,30.325000
75%,57.000000,85.000000,3.000000,152.000000,195.000000,1.000000,50.666667,55.250000,44.857500
max,83.000000,155.000000,4.000000,298.000000,294.000000,1.000000,99.333333,83.300000,95.920000

In [ ]:
# we have the lengths of all three "sides" of a triangle ((x_ft-11), (y_ft-150), distance_ft) so we can use trigonometry to solve for the angle